spring.application.name=backend

##spring.datasource.url=jdbc:postgresql://localhost:5432/_exa_VibeCheck
spring.datasource.url=jdbc:postgresql://postgres:5432/_exa_vibecheck

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create